failed merge_taxa unit test. Need to figure out why. But then in good shape.
  Running ‘testthat-phyloseq.R’
 ERROR
Running the tests in ‘tests/testthat-phyloseq.R’ failed.
Last 13 lines of output:
  5: attr.all.equal(target, current, tolerance = tolerance, scale =
scale, ...)
  6: mode(current)
  7: ntaxa(n1)

  4. Failure: merge_taxa() replaces disagreements in taxonomy with NA
------------
  sum(is.na(t951)) not equal to 1L
  Mean relative difference: 1

  5. Failure: merge_taxa() replaces disagreements in taxonomy with NA
------------
  is.na(t951[length(rank_names(n8))]) not equal to expected
  1 element mismatch
  Error: Test failures